// Expands the Direct3D shader the way the renderer does, and writes the result to stdout.
//
// The point is fidelity. The shader is compiled at RUNTIME from a template full of preprocessor
// directives, so nothing in the ordinary build ever looks at it -- a mistake in it ships, and surfaces as
// the game throwing out of CreateAndLoadNewShader the first time the affected variant is needed. This
// reproduces the string the renderer hands to D3DCompile so it can be compiled ahead of that.
//
// It runs the project's own prism context and the renderer's own combiner helpers, the latter sliced out of
// gfx_direct3d11.cpp between its PRISM-HELPERS markers (see validate.sh). Copying them here instead would
// have been simpler and wrong: a copy drifts, and a drifted copy expands a shader the game does not build,
// which is the exact failure this tool exists to catch.
//
// Two things are deliberately NOT the renderer's: the shader is read from disk rather than from an archive,
// and the combiner is one this program picks rather than one a scene produced. The first is unavoidable
// without the resource manager. The second is a real limit -- see the README.
#include <prism/processor.h>

#include <cstdint>
#include <fstream>
#include <iostream>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

// Taken from the header the renderer builds against rather than restated, because a copy of this number
// drifting is exactly the failure this tool exists to catch: the shader indexes an array sized by it, so a
// stale value here validates a shader the game does not build. The include path is set by validate.sh.
#include "fast/shadow_map.h"
#define SHADER_MAX_TEXTURES 6

enum {
    SHADER_0, SHADER_INPUT_1, SHADER_INPUT_2, SHADER_INPUT_3, SHADER_INPUT_4, SHADER_INPUT_5,
    SHADER_INPUT_6, SHADER_INPUT_7, SHADER_TEXEL0, SHADER_TEXEL0A, SHADER_TEXEL1, SHADER_TEXEL1A,
    SHADER_1, SHADER_COMBINED, SHADER_NOISE
};

// Mirrors CCFeatures. Declared here rather than included because fast/interpreter.h pulls in the resource
// system and the whole renderer with it; only the fields the prism context reads are needed.
struct CCFeatures {
    int c[2][2][4];
    bool opt_alpha, opt_fog, opt_texture_edge, opt_noise, opt_2cyc, opt_alpha_threshold;
    bool opt_invisible, opt_grayscale, opt_toon, opt_shadow_map;
    bool usedTextures[2], used_masks[2], used_blend[2], clamp[2][2];
    int numInputs;
    bool do_single[2][2], do_multiply[2][2], do_mix[2][2], color_alpha_same[2];
    int16_t shader_id;
};

#include "prism_helpers.inc" // generated by validate.sh from gfx_direct3d11.cpp

static std::string gShaderDir;

static std::optional<std::string> include_from_disk(const std::string& path) {
    std::ifstream f(gShaderDir + "/" + path);
    if (!f) {
        return std::nullopt;
    }
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "usage: prism_driver <shader.hlsl> <shaders-root> [options]\n"
                     "  options: any of 't' (toon), 's' (shadow map), 'f' (fog), '2' (two cycle),\n"
                     "           'a' (alpha threshold), 'n' (noise dither),\n"
                     "           'O' (opaque -- build the NO-alpha combiner instead of the alpha one)\n";
        return 2;
    }
    gShaderDir = argv[2];
    const std::string opts = argc > 3 ? argv[3] : "";
    auto has = [&opts](char c) { return opts.find(c) != std::string::npos; };

    CCFeatures cc{};
    // One textured input with alpha: the shape of ordinary scene geometry, and enough for the combiner to
    // expand into something representative.
    cc.c[0][0][0] = cc.c[1][0][0] = SHADER_TEXEL0;
    cc.c[0][1][0] = cc.c[1][1][0] = SHADER_TEXEL0A;
    // Opaque geometry is a DIFFERENT shader, not the same one with a channel ignored: without alpha the
    // vertex inputs are float3 instead of float4 and several combiner paths expand differently. Every
    // option set used to be built with alpha on, so half the shapes the game compiles were never seen here
    // -- and the variant that took the game down was one of them.
    cc.opt_alpha = !has('O');
    cc.usedTextures[0] = true;
    cc.numInputs = 1;
    cc.do_single[0][0] = cc.do_single[0][1] = cc.do_single[1][0] = cc.do_single[1][1] = true;
    cc.opt_toon = has('t');
    cc.opt_shadow_map = has('s');
    cc.opt_fog = has('f');
    cc.opt_2cyc = has('2');
    // The alpha cutoff has two placements -- hoisted above the shading, or left in the tail where the noise
    // dither can still move alpha under it -- so both need building. Neither was reachable before.
    cc.opt_alpha_threshold = has('a');
    cc.opt_noise = has('n');

    prism::Processor processor;
    prism::ContextItems ctx = {
        { "SHADER_0", SHADER_0 },
        { "SHADER_INPUT_1", SHADER_INPUT_1 },
        { "SHADER_INPUT_2", SHADER_INPUT_2 },
        { "SHADER_INPUT_3", SHADER_INPUT_3 },
        { "SHADER_INPUT_4", SHADER_INPUT_4 },
        { "SHADER_INPUT_5", SHADER_INPUT_5 },
        { "SHADER_INPUT_6", SHADER_INPUT_6 },
        { "SHADER_INPUT_7", SHADER_INPUT_7 },
        { "SHADER_TEXEL0", SHADER_TEXEL0 },
        { "SHADER_TEXEL0A", SHADER_TEXEL0A },
        { "SHADER_TEXEL1", SHADER_TEXEL1 },
        { "SHADER_TEXEL1A", SHADER_TEXEL1A },
        { "SHADER_1", SHADER_1 },
        { "SHADER_COMBINED", SHADER_COMBINED },
        { "SHADER_NOISE", SHADER_NOISE },
        { "o_c", M_ARRAY(cc.c, int, 2, 2, 4) },
        { "o_alpha", cc.opt_alpha },
        { "o_fog", cc.opt_fog },
        { "o_texture_edge", cc.opt_texture_edge },
        { "o_noise", cc.opt_noise },
        { "o_2cyc", cc.opt_2cyc },
        { "o_alpha_threshold", cc.opt_alpha_threshold },
        { "o_invisible", cc.opt_invisible },
        { "o_grayscale", cc.opt_grayscale },
        { "o_toon", cc.opt_toon },
        { "o_shadow_map", cc.opt_shadow_map },
        { "o_shadow_max_cascades", SHADOW_MAP_MAX_CASCADES },
        { "o_shadow_actor_cascades", SHADOW_MAP_ACTOR_CASCADES },
        { "o_textures", M_ARRAY(cc.usedTextures, bool, 2) },
        { "o_masks", M_ARRAY(cc.used_masks, bool, 2) },
        { "o_blend", M_ARRAY(cc.used_blend, bool, 2) },
        { "o_clamp", M_ARRAY(cc.clamp, bool, 2, 2) },
        { "o_inputs", cc.numInputs },
        { "o_do_mix", M_ARRAY(cc.do_mix, bool, 2, 2) },
        { "o_do_single", M_ARRAY(cc.do_single, bool, 2, 2) },
        { "o_do_multiply", M_ARRAY(cc.do_multiply, bool, 2, 2) },
        { "o_color_alpha_same", M_ARRAY(cc.color_alpha_same, bool, 2) },
        { "o_root_signature", false },
        { "o_three_point_filtering", false },
        { "srgb_mode", false },
        { "append_formula", (InvokeFunc)prism_append_formula },
        { "update_floats", (InvokeFunc)update_raw_floats },
        // Every helper the renderer registers has to be registered here too. The DEFINITIONS come across in
        // the sliced include and so cannot drift, but this list is a copy, and a copy did drift: the packed
        // vertex-colour work added update_packed_color to the renderer and not to this, which left the tool
        // aborting on prism::SyntaxError before it compiled a single variant. A validator that cannot run
        // reports nothing and looks like a validator that passed.
        { "update_packed_color", (InvokeFunc)update_packed_color },
    };
    processor.populate(ctx);

    std::ifstream in(argv[1]);
    if (!in) {
        std::cerr << "cannot read " << argv[1] << "\n";
        return 2;
    }
    std::stringstream ss;
    ss << in.rdbuf();
    std::string src = ss.str();
    processor.load(src);
    processor.bind_include_loader(include_from_disk);
    std::cout << processor.process();
    return 0;
}
